create table
  public.reviews (
    id bigint generated by default as identity not null,
    name character varying not null,
    email character varying null,
    review text not null,
    created_at timestamp with time zone null default now(),
    constraint reviews_pkey primary key (id)
  ) tablespace pg_default;
